### ISSUE TITLE
404 error on download 

### ISSUE THREAD

**Issue by jurriaanbos** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#34]
Hi Wouter,

Do you have any idea why I am getting this error?

2024-09-12 14:34:25.023 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/archive/refs/heads/d294ebf.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 709, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/archive/refs/heads/d294ebf.zip
2024-09-12 14:34:25.025 ERROR (MainThread) [custom_components.hacs] [<Integration WouterTuinstra/Homeassistant-Growatt-Local-Modbus>] Failed to download zipball
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 631, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 677, in download_repository_zip
    raise HacsException(f"[{self}] Failed to download zipball")
custom_components.hacs.exceptions.HacsException: [<Integration WouterTuinstra/Homeassistant-Growatt-Local-Modbus>] Failed to download zipball

**Comment by WouterTuinstra** [comment]
Hi, I'm not sure but to me, it seems to be a HACS issue
