### ISSUE TITLE
wrong constants (soon) and aliasses plus not working with growatt SPH model. How can this be fixed?

### ISSUE THREAD

**Issue by notalotofexperience** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#39]
2024-12-21 19:07:43.850 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration growatt_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-21 19:07:43.858 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-21 19:08:00.187 WARNING (ImportExecutor_0) [homeassistant.backports.enum] StrEnum was used from growatt_local, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'growatt_local' custom integration
2024-12-21 19:08:03.431 WARNING (ImportExecutor_0) [homeassistant.const] ELECTRIC_CURRENT_AMPERE was used from growatt_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please report it to the author of the 'growatt_local' custom integration
2024-12-21 19:08:03.445 WARNING (ImportExecutor_0) [homeassistant.const] ELECTRIC_POTENTIAL_VOLT was used from growatt_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please report it to the author of the 'growatt_local' custom integration
2024-12-21 19:08:03.457 WARNING (ImportExecutor_0) [homeassistant.const] ENERGY_KILO_WATT_HOUR was used from growatt_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'growatt_local' custom integration
2024-12-21 19:08:03.479 WARNING (ImportExecutor_0) [homeassistant.const] FREQUENCY_HERTZ was used from growatt_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfFrequency.HERTZ instead, please report it to the author of the 'growatt_local' custom integration
2024-12-21 19:08:03.491 WARNING (ImportExecutor_0) [homeassistant.const] POWER_WATT was used from growatt_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'growatt_local' custom integration
2024-12-21 19:08:03.503 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from growatt_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'growatt_local' custom integration
2024-12-21 19:08:03.515 WARNING (ImportExecutor_0) [homeassistant.const] TIME_HOURS was used from growatt_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.HOURS instead, please report it to the author of the 'growatt_local' custom integration
2024-12-21 19:08:03.522 DEBUG (MainThread) [custom_components.growatt_local] Finished fetching growatt_local data in 0.000 seconds (success: True)
2024-12-21 19:08:03.553 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.energy_produced_today for domain sensor with platform growatt_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 677, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: 'unavailable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 679, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.energy_produced_today has device class 'energy', state class 'total_increasing' unit 'kWh' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unavailable' (<class 'str'>)
2024-12-21 19:08:03.569 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.total_energy_produced for domain sensor with platform growatt_local

**Comment by Datawattchems** [comment]
[](url)
[home-assistant_growatt_local_2024-12-21T18-09-47.743Z.log](https://github.com/user-attachments/files/18219525/home-assistant_growatt_local_2024-12-21T18-09-47.743Z.log)
